/*
 * JNWNTFrame.java
 *
 * Created on March 29, 2004, 8:34 PM
 */

package jnwntreasure.presentation;

import javax.swing.*;
/**
 * @author  Jason Mazzotta
 */

/**
 * TBD
 */
public class JNWNTFrame extends javax.swing.JFrame {
    
    /** Creates new form jnwntreasure */
    public JNWNTFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        tableTree = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        createButton = new javax.swing.JButton();
        afterButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        propButton = new javax.swing.JButton();
        tabPropButton = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        deleteButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newItem = new javax.swing.JMenuItem();
        openItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        saveAsItem = new javax.swing.JMenuItem();
        closeItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exportItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        exitItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        insNewInItem = new javax.swing.JMenuItem();
        insNewAftItem = new javax.swing.JMenuItem();
        insTabItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        propsItem = new javax.swing.JMenuItem();
        tabPropsItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        moveUpItem = new javax.swing.JMenuItem();
        moveDownItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        deleteItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        tableTree.setPreferredSize(new java.awt.Dimension(640, 480));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        getContentPane().add(tableTree, gridBagConstraints);

        jToolBar1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        newButton.setText("New");
        //ImageIcon test = new ImageIcon("../../images/toolbar2.jpg");

	//if(test == null)
	//	System.out.println("Something isn't right here");
        //newButton.setIcon(test);
        jToolBar1.add(newButton);

        openButton.setText("Open");
        //openButton.setIcon(new ImageIcon("../../images/toolbar1.jpg","Open"));
        jToolBar1.add(openButton);

        saveButton.setText("Save");
        //saveButton.setIcon(new ImageIcon("../../images/toolbar5.jpg","Save"));
        jToolBar1.add(saveButton);

        jToolBar1.add(jSeparator6);

        createButton.setText("Create In");
        //createButton.setIcon(new ImageIcon("../../images/toolbar8.jpg","Create In"));
        jToolBar1.add(createButton);

        afterButton.setText("After");
        //afterButton.setIcon(new ImageIcon("../../images/toolbar10.jpg","After"));
        jToolBar1.add(afterButton);

        tableButton.setText("Table");
        //tableButton.setIcon(new ImageIcon("../../images/toolbar7.jpg","Table"));
        jToolBar1.add(tableButton);

        jToolBar1.add(jSeparator7);

        propButton.setText("Prop.");
        //propButton.setIcon(new ImageIcon("../../images/toolbar6.jpg","Prop."));
        jToolBar1.add(propButton);

        tabPropButton.setText("Table Prop.");
        //tabPropButton.setIcon(new ImageIcon("../../images/toolbar9.jpg","Table Prop."));
        jToolBar1.add(tabPropButton);

        jToolBar1.add(jSeparator8);

        deleteButton.setText("Delete");
        //deleteButton.setIcon(new ImageIcon("../../images/toolbar3.jpg","Delete"));
        jToolBar1.add(deleteButton);

        jToolBar1.add(jSeparator9);

        upButton.setText("Up");
        //upButton.setIcon(new ImageIcon("../../images/toolbar11.jpg","Up"));
        jToolBar1.add(upButton);

        downButton.setText("Down");
        //downButton.setIcon(new ImageIcon("../../images/toolbar4.jpg","Down"));
        jToolBar1.add(downButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(jToolBar1, gridBagConstraints);

        fileMenu.setText("File");
        newItem.setText("New");
        fileMenu.add(newItem);

        openItem.setText("Open ...");
        fileMenu.add(openItem);

        saveItem.setText("Save");
        fileMenu.add(saveItem);

        saveAsItem.setText("Save As ...");
        saveAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsItemActionPerformed(evt);
            }
        });

        fileMenu.add(saveAsItem);

        closeItem.setText("Close");
        fileMenu.add(closeItem);

        fileMenu.add(jSeparator1);

        exportItem.setText("Export Script ...");
        fileMenu.add(exportItem);

        fileMenu.add(jSeparator2);

        exitItem.setText("Exit");
        fileMenu.add(exitItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        insNewInItem.setText("Insert New In");
        editMenu.add(insNewInItem);

        insNewAftItem.setText("Inster New After ...");
        editMenu.add(insNewAftItem);

        insTabItem.setText("Insert Table ...");
        editMenu.add(insTabItem);

        editMenu.add(jSeparator3);

        propsItem.setText("Properties ...");
        editMenu.add(propsItem);

        tabPropsItem.setText("Table Properties ...");
        editMenu.add(tabPropsItem);

        editMenu.add(jSeparator4);

        moveUpItem.setText("Move Up");
        editMenu.add(moveUpItem);

        moveDownItem.setText("Move Down");
        editMenu.add(moveDownItem);

        editMenu.add(jSeparator5);

        deleteItem.setText("Delete");
        editMenu.add(deleteItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");
        aboutItem.setText("About");
        helpMenu.add(aboutItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }//GEN-END:initComponents

    private void saveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsItemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_saveAsItemActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree tableTree;
    private javax.swing.JButton afterButton;
    private javax.swing.JButton upButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton tableButton;
    private javax.swing.JButton tabPropButton;
    private javax.swing.JButton propButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downButton;
    private javax.swing.JMenuItem newItem;
    private javax.swing.JMenuItem openItem;
    private javax.swing.JMenuItem moveDownItem;
    private javax.swing.JMenuItem moveUpItem;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JMenuItem tabPropsItem;
    private javax.swing.JMenuItem deleteItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuItem exportItem;
    private javax.swing.JMenuItem propsItem;
    private javax.swing.JMenuItem saveAsItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JMenuItem insNewAftItem;
    private javax.swing.JMenuItem insNewInItem;
    private javax.swing.JMenuItem insTabItem;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * TBD
     */
    public JTree getTableTree()
    {
    	return tableTree;
    }

    /**
     * TBD
     */
    public JButton getAfterButton()
    {
    	return afterButton;
    }

    /**
     * TBD
     */
    public JButton getUpButton()
    {
    	return upButton;
    }
    
    /**
     * TBD
     */
    public JButton getOpenButton()
    {
    	return openButton;
    }
    
    /**
     * TBD
     */
    public JButton getNewButton()
    {
    	return newButton;
    }
    
    /**
     * TBD
     */
    public JButton getTableButton()
    {
    	return tableButton;
    }
    
    /**
     * TBD
     */
    public JButton getTabPropButton()
    {
    	return tabPropButton;
    }
    
    /**
     * TBD
     */
    public JButton getPropButton()
    {
    	return propButton;
    }
    
    /**
     * TBD
     */
    public JButton getSaveButton()
    {
    	return saveButton;
    }    
 
    /**
     * TBD
     */
    public JButton getCreateButton()
    {
    	return createButton;
    }
    
    /**
     * TBD
     */
    public JButton getDeleteButton()
    {
    	return deleteButton;
    }
    
    /**
     * TBD
     */
    public JButton getDownButton()
    {
	return downButton;
    }
   
    /**
     * TBD
     */
    public JMenuItem getNewItem()
    {
    	return newItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getOpenItem()
    {
    	return openItem;
    }   
 
    /**
     * TBD
     */
    public JMenuItem getMoveDownItem()
    {
    	return moveDownItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getMoveUpItem()
    {
    	return moveUpItem;
    }

    /**
     * TBD
     */
    public JMenuItem getSaveItem()
    {
    	return saveItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getTabPropsItem()
    {
    	return tabPropsItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getDeleteItem()
    {
    	return deleteItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getExitItem()
    {
    	return exitItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getExportItem()
    {
    	return exportItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getPropsItem()
    {
    	return propsItem;
    }   
 
    /**
     * TBD
     */
    public JMenuItem getSaveAsItem()
    {
    	return saveAsItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getCloseItem()
    {
    	return closeItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getInsNewAftItem()
    {
    	return insNewAftItem;
    }   
 
    /**
     * TBD
     */
    public JMenuItem getInsNewInItem()
    {
    	return insNewInItem;
    }
    
    /**
     * TBD
     */
    public JMenuItem getInsTabItem()
    {
    	return insTabItem;
    }   
 
    /**
     * TBD
     */
    public JMenuItem getAboutItem()
    {
	return aboutItem;
    }
}
