/*
 * NonePanel.java
 *
 * Created on May 1, 2004, 3:08 PM
 */

package jnwntreasure.presentation;

/**
 * @author  Jason Mazzotta
 */
 
/**
 * TBD
 */
public class NonePanel extends javax.swing.JPanel {
    
    /** Creates new form NonePanel */
    public NonePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        chanceSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Chance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.1;
        add(chanceSpinner, gridBagConstraints);

    }//GEN-END:initComponents

    /**
     * TBD
     */
    public javax.swing.JSpinner getChanceSpinner()
    {
	return chanceSpinner;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner chanceSpinner;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
