/*
 * PlaceablePanel.java
 *
 * Created on May 1, 2004, 3:16 PM
 */

package jnwntreasure.presentation;

/**
 *
 * @author  Jason Mazzotta
 */

/**
 * TBD
 */
public class PlaceablePanel extends javax.swing.JPanel {
    
    /** Creates new form PlaceablePanel */
    public PlaceablePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        chanceSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        bluePrintCombo = new javax.swing.JComboBox();
        bluePrintButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Chance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.1;
        add(chanceSpinner, gridBagConstraints);

        jLabel2.setText("Placeable BluePrint");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        add(bluePrintCombo, gridBagConstraints);

        bluePrintButton.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        add(bluePrintButton, gridBagConstraints);

    }//GEN-END:initComponents
  
    /**
     * TBD
     */ 
    public javax.swing.JComboBox getBluePrintCombo()
    {
	return bluePrintCombo;
    }

    /**
     * TBD
     */
    public javax.swing.JButton getBluePrintButton()
    {
	return bluePrintButton;
    }
   
    /**
     * TBD
     */
    public javax.swing.JSpinner getChanceSpinner()
    {
	return chanceSpinner;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bluePrintCombo;
    private javax.swing.JButton bluePrintButton;
    private javax.swing.JSpinner chanceSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
