/*
 * TableDlg.java
 *
 * Created on April 7, 2004, 10:55 PM
 */

package jnwntreasure.presentation;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;


/**
 *
 * @author Jason Mazzotta 
 */

/**
 * TBD
 */
public class TableDlg extends javax.swing.JDialog {
    
    /** Creates new form TableDlg */
    public TableDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        modeComboBox = new javax.swing.JComboBox();
        globalTabCheck = new javax.swing.JCheckBox();
        tabNumLabel = new javax.swing.JLabel();
        tabNumSpinner = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setResizable(false);
        jLabel1.setText("Table Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(nameField, gridBagConstraints);

        jLabel2.setText("Decision Mode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(modeComboBox, gridBagConstraints);

        globalTabCheck.setText("Global Table - Global Tables will be made available as starting points.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(globalTabCheck, gridBagConstraints);

        tabNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabNumLabel.setText("Table Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(tabNumLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(tabNumSpinner, gridBagConstraints);

        cancelButton.setText("Cancel");
        okButton.setText("OK");
        okButton.setPreferredSize(cancelButton.getPreferredSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(okButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
   
    /**
     * TBD
     */ 
    public JButton getOK()
    {
        return okButton;
    }

    /**
     * TBD
     */ 
    public JButton getCancel()
    {
        return cancelButton;
    }
    
    /**
     * TBD
     */ 
    public JComboBox getModeComboBox()
    {   
        return modeComboBox;
    }
    
    /**
     * TBD
     */ 
    public JCheckBox getGlobalTabCheck()
    {
        return globalTabCheck;
    }
    
    /**
     * TBD
     */ 
    public JLabel getTabNumLabel()
    {
        return tabNumLabel;
    }
    
    /**
     * TBD
     */ 
    public JSpinner getTabNumSpinner()
    {
        return tabNumSpinner;
    }
    
    /**
     * TBD
     */ 
    public JTextField getNameField()
    {
        return nameField;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox globalTabCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox modeComboBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel tabNumLabel;
    private javax.swing.JSpinner tabNumSpinner;
    // End of variables declaration//GEN-END:variables
    
}
