// -*- C++ -*- generated by wxGlade 0.2.3 on Wed Oct 08 11:52:39 2003

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade


#ifndef PROITEMPROPDLG_H
#define PROITEMPROPDLG_H


class ProItemPropDlg: public wxDialog {
    public:
        // begin wxGlade: ProItemPropDlg::ids
        // end wxGlade

        ProItemPropDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    private:
        // begin wxGlade: ProItemPropDlg::methods
        void set_properties();
        void do_layout();
        // end wxGlade

    protected:
        // begin wxGlade: ProItemPropDlg::attributes
        wxStaticText* label_1;
        wxTextCtrl* text_1;
        wxStaticText* label_2;
        wxChoice* choice_1;
        wxStaticText* label_3;
        wxSpinCtrl* spin_1;
        wxStaticText* label_4;
        wxChoice* choice_2;
        wxButton* button_1;
        wxStaticText* label_5;
        wxChoice* choice_3;
        wxButton* button_2;
        wxStaticText* label_6;
        wxTextCtrl* text_2;
        wxStaticText* label_7;
        wxSpinCtrl* spin_2;
        wxStaticText* label_8;
        wxChoice* choice_4;
        wxButton* button_OK;
        wxButton* button_Cancel;
        // end wxGlade
};


#endif // PROITEMPROPDLG_H

/* vim: set sw=4: */
