// -*- C++ -*- generated by wxGlade 0.2.3 on Fri Aug 15 10:34:27 2003

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade


#ifndef TABLEPROPDLG_H
#define TABLEPROPDLG_H

enum
{
    ID_GlblCheckbox,
};

class TblPropDialog: public wxDialog {
    public:
        // begin wxGlade: TblPropDialog::ids
        // end wxGlade

        TblPropDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

        wxString GetTblName();

        wxString GetName();
        wxString GetMode();
        bool GetGlobal();
        int GetTblNum();

        void SetName(wxString);
        void SetMode(wxString);
        void SetGlobal(bool);
        void SetTblNum(int);

    private:
        // begin wxGlade: TblPropDialog::methods
        void set_properties();
        void do_layout();
        // end wxGlade

        void OnOk(wxCommandEvent &event);
        void OnGlblCheck(wxCommandEvent &event);

    protected:
        // begin wxGlade: TblPropDialog::attributes
        wxStaticText* label_TblName;
        wxTextCtrl* text_TblName;
        wxStaticText* label_DMode;
        wxComboBox* combo_box_1;
        wxCheckBox* checkbox_1;
        wxStaticText* label_1;
        wxStaticText* label_TblNum;
        wxSpinCtrl* spin_ctrl_1;
        wxButton* button_1;
        wxButton* button_2;
        // end wxGlade

    private:
        DECLARE_EVENT_TABLE()

};

#endif // TABLEPROPDLG_H

/* vim: set sw=4: */
